FROM ghcr.io/linuxserver/baseimage-selkies:arch

ARG BUILD_DATE
ARG VERSION
LABEL build_version="Custom Arch Plex HTPC image - Build-date:- ${BUILD_DATE}"
LABEL maintainer="Serph91P"

ENV TITLE="Plex HTPC" \
    NO_GAMEPAD=false \
    NO_DECOR=true \
    SELKIES_DESKTOP=false \
    PIXELFLUX_WAYLAND=true

RUN \
  echo "**** update system to latest ****" && \
  pacman -Syu --noconfirm && \
  echo "**** install runtime packages ****" && \
  pacman -S --noconfirm --needed \
    alsa-lib \
    base-devel \
    dbus \
    expat \
    ffmpeg \
    fontconfig \
    freetype2 \
    gcc-libs \
    git \
    glib2 \
    harfbuzz \
    hicolor-icon-theme \
    lcms2 \
    libdrm \
    libjpeg-turbo \
    libpulse \
    libva \
    libwebp \
    libx11 \
    libxcb \
    libxcomposite \
    libxdamage \
    libxext \
    libxfixes \
    libxinerama \
    libxkbcommon \
    libxkbcommon-x11 \
    libxkbfile \
    libxml2-legacy \
    libxrandr \
    libxrender \
    libxslt \
    libxss \
    libxtst \
    mesa \
    minizip \
    nspr \
    nss \
    opus \
    pciutils \
    qt6-base \
    qt6-wayland \
    snappy \
    squashfs-tools \
    vulkan-radeon \
    wayland \
    xcb-util-image \
    xcb-util-keysyms \
    xcb-util-renderutil \
    xcb-util-wm \
    zlib && \
  echo "**** build Plex HTPC from AUR ****" && \
  useradd -m builder && \
  echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder && \
  chmod 0440 /etc/sudoers.d/builder && \
  sudo -u builder git clone https://aur.archlinux.org/plex-htpc.git /tmp/plex-htpc && \
  cd /tmp/plex-htpc && \
  sudo -u builder makepkg -si --noconfirm --needed && \
  echo "**** add icon ****" && \
  cp /usr/share/icons/hicolor/256x256/apps/tv.plex.PlexHTPC.png /usr/share/selkies/www/icon.png && \
  echo "**** set bash as default shell ****" && \
  sed -i 's|/bin/sh$|/bin/bash|g' /etc/passwd && \
  echo "**** create user directories ****" && \
  mkdir -p /config/Documents && \
  echo "**** cleanup ****" && \
  userdel -r builder || true && \
  rm -rf \
    /config/.cache \
    /etc/sudoers.d/builder \
    /tmp/* \
    /var/cache/pacman/pkg/* \
    /var/lib/pacman/sync/*

COPY /root-plex /

EXPOSE 3000

VOLUME /config
