FROM ghcr.io/linuxserver/baseimage-selkies:arch

ARG BUILD_DATE
ARG VERSION
ARG CACHE_BUST
LABEL build_version="Custom Arch Plezy image - Build-date:- ${BUILD_DATE}"
LABEL maintainer="Serph91P"

# Only Plezy app, no desktop environment auto-start
ENV TITLE="Plezy" \
    PIXELFLUX_WAYLAND=true \
    SELKIES_DESKTOP=false \
    AUTO_GPU=true \
    NO_GAMEPAD=true \
    NO_DECOR=true

RUN \
  echo "**** cache bust ${CACHE_BUST} ****" && \
  echo "**** update system to latest ****" && \
  pacman -Syu --noconfirm && \
  echo "**** install runtime packages ****" && \
  pacman -S --noconfirm --needed \
    base-devel \
    dbus \
    git \
    gtk3 \
    gwenview \
    kcm-wacomtablet \
    kconfig \
    kcoreaddons \
    kdecoration \
    kdesdk-kate-part \
    kio \
    konsole \
    kwayland \
    kwayland-integration \
    kwidgetsaddons \
    kwin \
    libepoxy \
    libevdev \
    mpv \
    plasma-desktop \
    plasma-integration \
    plasma-systemstats \
    sddm-kcm \
    spectacle \
    xwayland \
    yakuake && \
  echo "**** build Plezy from AUR ****" && \
  useradd -m builder && \
  echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder && \
  chmod 0440 /etc/sudoers.d/builder && \
  sudo -u builder git clone https://aur.archlinux.org/plezy-bin.git /tmp/plezy-bin && \
  cd /tmp/plezy-bin && \
  sudo -u builder makepkg -s --noconfirm --needed && \
  pacman -U --noconfirm /tmp/plezy-bin/*.pkg.tar.zst && \
  (test -x /usr/bin/plezy || test -x /opt/plezy/plezy) && \
  echo "**** add icon ****" && \
  cp /usr/share/icons/hicolor/256x256/apps/plezy.png /usr/share/selkies/www/icon.png && \
  echo "**** set bash as default shell ****" && \
  sed -i 's|/bin/sh$|/bin/bash|g' /etc/passwd && \
  echo "**** create user directories ****" && \
  mkdir -p /config/Documents && \
  echo "**** cleanup ****" && \
  userdel -r builder || true && \
  rm -rf \
    /config/.cache \
    /etc/sudoers.d/builder \
    /tmp/* \
    /var/cache/pacman/pkg/* \
    /var/lib/pacman/sync/*

# Custom files: Plezy autostart for LinuxServer Selkies session
COPY root-plex/ /

RUN chmod +x /defaults/autostart /defaults/autostart_wayland /defaults/startwm_wayland.sh /usr/local/bin/run-plex && \
    echo "**** verify final Plezy image contents ****" && \
    ls -la /usr/bin/plezy /opt/plezy/plezy && \
    (/usr/local/bin/run-plex --version >/tmp/plezy-version.log 2>&1 || true) && \
    touch /tmp/plezy-version.log && \
    cat /tmp/plezy-version.log

EXPOSE 3000

VOLUME /config